### ISSUE TITLE
Gitに関するおすすめの情報

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-ja/stan-ja#1]
メンバーの中には研究者が多いと思いますのでGitのよかった本を紹介したいと思います。
「Gitが、おもしろいほどわかる基本の使い方33〈バージョン管理、SourceTree、Bitbucket〉」です。
http://www.amazon.co.jp/dp/4844365010/
BitbucketというGithubの競合サービスを使った内容ですがほとんどそのままGithubにも適用できます。SourceTreeの使い方もMac版とWindows版の説明があって丁寧でした。

**Comment by soogie** [comment]
まさにBitbucketとSourcetreeを使ってMacとWindowsを行ったり来たりしてますが、コミット、プル、プッシュしか使えていないので、購入して参考にしたいと思います。ありがとうございます。
