### ISSUE TITLE
CircleCI 2.0対応

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-ja/stan-ja#101]
CircleCI 1.0のサポートが切れるようで、FAILEDになっている。
https://circleci.com/gh/stan-ja/stan-ja
更新手順はこちら。
https://circleci.com/sunset1-0/

**Comment by MatsuuraKentaro** [comment]
@kos59125 もし経験があればやっていただけないでしょうか？

**Comment by kos59125** [comment]
Fail の理由は 2.0 とは関係ないっぽいですが、対応します。

**Comment by MatsuuraKentaro** [comment]
すみません。ありがと！！！
