### ISSUE TITLE
CircleCIでエラー

### ISSUE THREAD

**Issue by ito4303** [stan-ja/stan-ja#104]
Pull Requestを出してある訳文を更新してpushしたところ、CircleCIでエラーが発生しました。

https://circleci.com/gh/stan-ja/stan-ja/434?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

エラーは以下のようなものです。

``
W: GPG error: https://apt.dockerproject.org ubuntu-precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

Current status: 1485 updates [+139], 3400 new [+3400].
There are 10 newly obsolete packages: alex-3.1.3, cabal-install-1.22,
                                      ghc-7.10.1, ghc-7.10.2, ghc-7.4.2,
                                      ghc-7.6.3, ghc-7.8.2, ghc-7.8.3,
                                      ghc-7.8.4, happy-1.19.3

sudo aptitude update -y returned exit code 255

Action failed: sudo aptitude update -y
``

**Comment by kos59125** [comment]
#101 で新しいバージョンの Circle CI の設定を行っているので、 master をマージして試してみてもらってもよいでしょうか。

```bash
$ git checkout master
$ git pull origin master
$ git checkout <your-working-branch>
$ git merge master
$ git push origin <your-working-branch>
```

`merge` は `rebase` でもよいです。 `rebase` の場合 `push` する際に `--force` が必要になるかもしれません。

**Comment by ito4303** [comment]
All checks have passed になりました。ありがとうございます。

`rebase master`としたところ、これまでのmasterでの変更もこのブランチに含まれる
ようになったのですが、これはそういうもの&問題ない、と思ってよいでしょうか。

**Comment by ito4303** [comment]
なんだかマズそうな気がしてきたので、古いブランチはいったん消して、あらためてPull requestを出すことにしました。

**Comment by ito4303** [comment]
`merge master`だとうまくいくことがわかりました。
ということで、このIssueはCloseします。
