### ISSUE TITLE
[要望] 最新の PDF へのリンクが Readme にほしい

### ISSUE THREAD

**Issue by kos59125** [stan-ja/stan-ja#16]
#12 より転載

> 要望ですが、現在のmasterすべてを使ってpdfにしたものへのリンクがReadmeにあるといいなぁと思うのですが、実現できるものでしょうか？

**Comment by kos59125** [comment]
@MatsuuraKentaro 
PDF はコミットごとに作成されて URL が変わるために README に書くのは少し難しいです。
実現するとしたら， PDF ができるたびに機械的に README を書き換えてコミットして GitHub に push するという流れになるかと思います。
例えば「README の先頭行は PDF へのリンクが機械的に編集されるために人手による編集は不可」とかそういうルールがあれば実現できるかなぁと思いますが，コンフリクトするかもしれないのでちょっと怖いです。

代替案としては， Wiki ページを利用したり， GitHub のリリース機能を利用して，そこに対して README から誘導するという方法があります。
- 原案
  - メリット: 常に最新版へのリンクがトップに現れる。
  - デメリット: README にルールが増える。コミット作業があるため，コンフリクトが起こるおそれがある。
- 代替案
  - メリット: README にルールが増えない。コミットがないため安全。
  - デメリット: 最新版 PDF に飛ぶためのリンク数が原案に比べて増える。

ちなみにコンフリクトが起こった場合の影響ですが，ビルドの結果が常にエラーになる (PDF はできるけどバッテンがつく) のと，常に古い (コンフリクト前の最新) 版へのリンクが修正するまで残り続けるという感じですかね。

**Comment by piroyoung** [comment]
web serverにデプロイできればそれも一つ解決策ですね．
circle ciのデプロイ先ってssh認証ができればそれでいいんでしょうか？
stan コミュニティに協力お願いしたらいい方法見つかるかもしれませんね

**Comment by MatsuuraKentaro** [comment]
Wiki ページを利用したり、GitHub のリリース機能を利用するのでまったくかまいません。
ただ、Wikiに載せるリンクもコミットごとにURLが変わるんですよね？それがちょっとめんどそう。

**Comment by kos59125** [comment]
#17 で実現したのでクローズします。
