### ISSUE TITLE
数式をTeX記法で書いてもレンダリングされない

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-ja/stan-ja#2]
Github上のMarkdown（mdファイル）ではレンダリングされないようです。
https://github.com/github/markup/issues/274

個人的には翻訳において数式を手間をかけて打ち直すことが重要とは思っておらず、画像でいいかなと思っているのでこのまま画像へのリンクを含んだmd形式ですすめたいと思っています。なお、最終的にはpandocというツールでTeXを経由してpdf化する予定でして、TeX記法で数式を書いておいても最終産物のpdfではちゃんとレンダリングされるようです。

Web上で数式を意地でも見る方法としては、R Markdown（Rmdファイル）を使ってhtml化する方法やjupyter notebookというツールを使う方法があります。

何か意見ありましたらコメント下さい。

**Comment by ozt-ca** [comment]
Mathjax$B$C$F;H$($J$$$s$G$7$?$C$1!)(B

-$BHx:j(B $BN4(B (TJO)

---

Takashi J. OZAKI, Ph. D.
E-mail: ozt.dei@gmail.com

2015/12/21 0:51$B!"(BMatsuuraKentaro notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by ozt-ca** [comment]
ごめんなさい、メールコメント機能使ったら文字化けしました。

本題ですが、Mathjaxは使えないんでしょうか？JSのタグで埋め込めば使えるのではと。

**Comment by soogie** [comment]
セキュリティ上の理由でMathjax含め使えないそうです。
http://stackoverflow.com/questions/11256433/how-to-show-math-equations-in-general-githubs-markdownnot-githubs-blog

上記をgithub/markupでissue立てた人がいてgithub側の回答がついています。

https://github.com/github/markup/issues/274

iTex2Imgを使うか、諦めて画像にするかですね。

**Comment by kos59125** [comment]
一応参考までに GitHub Pages のサンプル作成しました。
https://github.com/kos59125/test http://kos59125.github.io/test/
Markdown で Web 上ではそのまま数式いけます。

**Comment by soogie** [comment]
よく見たら私が書いているgithub/markupの回答は，そもそもberoberoさんが触れてましたね。失礼しました。
@kos59125 さんのおっしゃっているのは，githubのリポジトリ上ではレンダリングされないけど，github pagesでは大丈夫，ということでしょうか。

**Comment by kos59125** [comment]
GitHub Pages ではレンダリングされるという意味です。

本質的な問題は，スクリーンショットにしてしまうと数式情報が失われてしまうというところかなと思います。
レビューのために一時的に画像にしてしまうと，そのあと PDF に変換するのが大変になります。

TeX 形式で gh-pages に完全な状態が出力されるようになれば， HTML でも表示できるし， PDF を作成する際も簡単になります。

自分のブランチで Circle CI で PDF を自動ビルドするようにしてみました。
https://circle-artifacts.com/gh/kos59125/stan-ja/7/artifacts/0/tmp/circle-artifacts.a3JiXPj/stan-reference-2.9.0-ja-dev.pdf

CI に乗せるためには，スクリーンショット形式だと処理することができないため， TeX 形式で入力するのが必要になります。
さらに deployment の対象を gh-pages にすることで， HTML と PDF がいい感じに自動的に作り続けられる状態になります。

**Comment by kos59125** [comment]
これに関連して PR #6 を作成しました。

**Comment by MatsuuraKentaro** [comment]
現状の運用でほぼ解決しているのでいったんcloseします。

**Comment by MatsuuraKentaro** [comment]
インライン数式で問題が起きています。

コミットごとにpdfが作られるようになったのでmarkdownをGithub上でレンダリングしてのレビューはやめてもいいかなと思っています。しかし、いつかhtml化してWikiなりに移動したときに、そこでもちゃんと数式は読めるようにしたいと思っています（検索にヒットしますし）。

この2つを両立させるために、markdownでは [$ TeX記法 $](<var>D</var>)のような感じにして、pdfにする時は[]の中を、htmlにする時は()の中を使えるようにできないか模索中です。これはmdをhtml化する方法にも依存しているので、そちらも少し調べています。

**Comment by MatsuuraKentaro** [comment]
@kos59125 すみません、知恵をかしてください。一番ほしいのはpdfとhtmlで、github上での表示はおまけです。まず、CIでpdfを作成する時に、同時にhtmlも作成できて、リンクをpdfとhtmlの2つ表示することは可能でしょうか？それが可能として、考えた選択肢は以下の2つです。
- 初期発生率([<var>e</var>]($e$)) と書く
  - 欠点：そもそも書くのが面倒。pdfを作成する時には\$e\$だけを取得する正規表現を、htmlを作成する時には<var>e</var>だけ抽出する正規表現をかかなくてはいけない。
  - 利点：github上でもなんとなく表示される。
- 初期発生率(($e$)) と書いてTex表記だけにする。[HTMLにおける数式の表示](http://sky-y.github.io/site-pandoc-jp/users-guide/)にあるのようにpandocでhtmlに変換したのちにLaTeXMathMLを使って数式を表示する。
  - 欠点：github上では表示されない。
  - 利点：ラク。ルールがややこしくない。

いずれにせよkosさんしかできる人がいないので、判断をしてほしいです。実現可能ならば、現状では後者がいいかなと思っています。

**Comment by kos59125** [comment]
まず前提として Markdown は GitHub の要求する形式と pandoc の要求する形式が異なるので，両立は難しいです。
最終出力が目的であれば， GitHub での見栄えは多少我慢せざるをえないところがあります。

それで次に pandoc での処理の話ですが， pandoc を前提とするなら PDF と HTML の同時出力は容易だと思います。
また，記法も TeX 記法を使えば PDF 出力の時は数式モードに， HTML 出力の時は MathJax 形式に変換されます (実際はそのまま出力されて， MathJax が勝手に認識して処理してくれるのですが)。

ちなみに HTML ってレビュー用の単一チャプターのものですか？ それとも全体の HTML も？

**Comment by MatsuuraKentaro** [comment]
それならGithubの見栄えはあきらめて、TeX記法だけにしてpandocに一本化がよさそうですね。

> ちなみに HTML ってレビュー用の単一チャプターのものですか？ それとも全体の HTML も？

PDFと同じように、レビュー用には単一チャプターを、masterにとりこまれた場合は、全体のhtmlをどこか（Github Pages？Wiki？）に出力したいなと思っていました。ただし、全体の方は急ぎではなく、いつかできればいいなというぐらいです。
