### ISSUE TITLE
章の担当決め

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-ja/stan-ja#31]
章の担当を一部決めたいと思いますがいかがでしょうか。はじめは訳の様子を見たいので僕が決めますが、強く希望する章があれば移動するのも可能です。レビューは追って決めます。

| 章 | 翻訳 | レビュー | merged | 訳したversion |
| :-- | :-- | :-- | :-- | :-- |
| 1 | @piroyoung @MatsuuraKentaro | @ito4303 @hagijyun |  x | 2.12 |
| 2 | @soogie | @MatsuuraKentaro | x | 2.9 |
| 3 | @siero5335 | @MatsuuraKentaro | x | 2.9 |
| 4 | @siero5335 | @MatsuuraKentaro | x | 2.9 |
| 5 | @MatsuuraKentaro | @ito4303, @hagijyun | x | 2.11 |
| 6 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 7 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 8 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 9 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 10 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 11 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 12 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 13 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 14 | @hagijyun | @MatsuuraKentaro | x | 2.9 |
| 15 |  |  |  | 2.11 |
| 16 | @ito4303 | @MatsuuraKentaro | x | 2.12 |
| 17 | @MatsuuraKentaro | @hagijyun | x | 2.12 |
| 18 | @MatsuuraKentaro | @ito4303 | x | 2.12 |
| 19 | @MatsuuraKentaro | @ito4303 @hagijyun | x | 2.11 |
| 20 | @MatsuuraKentaro | @ito4303 @hagijyun | x | 2.11 |
| 21 | @ito4303  | @MatsuuraKentaro | x | 2.12 |
| 22 |  |  |  | 2.11 |
| 23 | @soogie | @kos59125 @MatsuuraKentaro | x | 2.9 |
| 24 | @ymattu |  |  | 2.11 |
| 25 | @hoxo-m |  |  | 2.11 |
| 26 |  @ito4303 |  @hagijyun |  x | 2.14 |
| 27 | @sinhrks | @MatsuuraKentaro |  | 2.10  (#49) |
| 28 |  |  |  | 2.11 |
| 29 |  |  |  | 2.11 |
| 30 | @soogie |  |  | 2.11 |
| 31 | @ymattu |  |  | 2.11 |
| 32 | @ymattu |  |  | 2.11 |
| 33 | @yuifu |  |  | 2.11 |
| 34 |  |  |  | 2.11 |
| 35 |  |  |  | 2.11 |
| 36 |  |  |  | 2.11 |
| 37 |  |  |  | 2.11 |
| 38 | @ozt-ca |  |  | 2.11 |
| 39 | @ozt-ca |  |  | 2.11 |
| 40 |  |  |  | 2.11 |
| 41 |  |  |  | 2.11 |
| 42 |  |  |  | 2.11 |
| 43 |  |  |  | 2.11 |
| 44 |  |  |  | 2.11 |
| 45 |  |  |  | 2.11 |
| 46 |  |  |  | 2.11 |
| 47 |  |  |  | 2.11 |
| 48 |  |  |  | 2.11 |
| 49 |  |  |  | 2.11 |
| 50 |  |  |  | 2.11 |
| 51 |  |  |  | 2.11 |
| 52 |  |  |  | 2.11 |
| 53 |  |  |  | 2.11 |
| 54 |  |  |  | 2.11 |
| 55 | @ito4303 | @MatsuuraKentaro | x | 2.9 |
| 56 | @ito4303 | @MatsuuraKentaro | x | 2.11 |
| 57 | @ito4303 | @hagijyun @MatsuuraKentaro | x | 2.11 |
| 58 | @xiangze |  |  | 2.11 |
| 59 | @xiangze |  |  | 2.11 |
| 60 | @xiangze | @kos59125 @teramonagi @MatsuuraKentaro |  | 2.9 |
| 61 |  |  |  | 2.11 |
| 62 |  |  |  | 2.11 |
| 63 |  |  |  | 2.11 |
| 64 |  |  |  | 2.11 |
| 65 |  |  |  | 2.11 |
| A |  |  |  | 2.11 |
| B |  |  |  | 2.11 |
| C |  |  |  | 2.11 |
| D |  |  |  | 2.11 |
| E |  |  |  | 2.11 |

ちょっと翻訳つらいのでグループ抜けますという人はご連絡ください。特にマイナスの感情もありませんのでご自由にお願いします。

**Comment by soogie** [comment]
2章に私の名前が入っていますが@MatsuuraKentaroさんが翻訳済みではないですか？
22章はmerge済みですね。29章は用語がわからず悪戦苦闘中です。若い章の翻訳が進めば用語がわかってくるかなと少し置いていますが，引き続きがんばります。

**Comment by ymattu** [comment]
@MatsuuraKentaro 私は自分の箇所に関してはこれで構いません。期限があればお知らせください。

**Comment by MatsuuraKentaro** [comment]
@soogie さん、2章は僕が少しだけ訳しましたが、他のレビューが忙しいのでぜひ残りをお願いしたいです。29章などは難しいですね。無理なさらず。

@ymattu さん、ありがとうございます。期限ははじめはなしで。またみなさんの進捗が特になければ、次は設定します（笑）

**Comment by hoxo-m** [comment]
24章 Data Types and Variable Declarations ですね。ぜひやらせてください！

**Comment by MatsuuraKentaro** [comment]
@hoxo-m おお、ありがとうございます！是非お願いします！

**Comment by soogie** [comment]
@MatsuuraKentaroさん、2章の件承知しました。最初のパートなのでこちらを先にやりますね。

**Comment by xiangze** [comment]
レビューができましたら56,57章をやらせていただけないでしょうか。

**Comment by ito4303** [comment]
13章をやります。

**Comment by MatsuuraKentaro** [comment]
@xiangze @ito4303 ありがとうございます。お願いします。

**Comment by ito4303** [comment]
53章をやります。

**Comment by MatsuuraKentaro** [comment]
@ito4303 ありがとうございます。よろしくお願いします。

**Comment by hagijyun** [comment]
14章を担当させていただきたいと思います。よろしくお願いします。

**Comment by MatsuuraKentaro** [comment]
@hagijyun ありがとうございます！よろしくお願いします。

**Comment by ito4303** [comment]
2.10の56章（Bayesian Data Analysis, 2.9の54章）をやります。

**Comment by MatsuuraKentaro** [comment]
よろしくお願いします！

**Comment by ito4303** [comment]
57章をやります。

**Comment by MatsuuraKentaro** [comment]
ありがとうございます。宜しくお願いします。

**Comment by ito4303** [comment]
つぎは16章をやります。

**Comment by MatsuuraKentaro** [comment]
よろしくお願いします！

**Comment by MatsuuraKentaro** [comment]
Stan 2.12のマニュアルが出ました。以降、新しく翻訳を開始する人は2.12でお願いします。

**Comment by ito4303** [comment]
21章をやります。

**Comment by MatsuuraKentaro** [comment]
よろしくお願いします！

**Comment by ito4303** [comment]
Stan 2.14 マニュアルは、4〜6章あたりの構成がけっこう変わってますね。

**Comment by MatsuuraKentaro** [comment]
確認ありがとうございます。target記法になりましたし、一度diffをとってみなきゃですね…

**Comment by soogie** [comment]
私もStan2.14マニュアル見ました。全体的にいろいろ変わっていて，自分が次にどこを訳せばいいか，わからなくなってしまいました。
2.9マニュアルのChap30はVoid Functionsですね。それが2.12ではChap31，2.14ではChap37になっています。私の割り当ては2.9のChap30だったので，2.14のChap37を訳す，ということで大丈夫でしょうか？

**Comment by MatsuuraKentaro** [comment]
立て込んでいまして、チェックできずにすみません。各自の判断で自由に変えてもらってPR送ってもらって構わないと思います。そして、誰かレビューすればよいかと。

**Comment by soogie** [comment]
承知しました〜

**Comment by ito4303** [comment]
2.12の26章（2.14の3章）をやります。

**Comment by MatsuuraKentaro** [comment]
すみませんが、よろしくお願いします。

**Comment by MatsuuraKentaro** [comment]
フォルダ構造を変えたのでいったんcloseします。
