### ISSUE TITLE
Release の HTML に画像が表示されない

### ISSUE THREAD

**Issue by kos59125** [stan-ja/stan-ja#33]
HTML の画像リンクが修正されていないので，画像が表示されません。
埋め込み式にするかリンクにするか検討中。
- 埋め込み式にする場合: base64 エンコードする。ファイルが重くなる。
- リンクにする場合: Git のハッシュを使って GitHub にリンクする。ファイルが軽くなるが GitHub へのリンクを入れて良いのか悩む。

**Comment by MatsuuraKentaro** [comment]
画像は完璧です! ありがとうございました。TeXはどうもうまくいっていないみたいなので別issueたてますね。
