### ISSUE TITLE
プルリクをあげたところCircleCIのエラー

### ISSUE THREAD

**Issue by soogie** [stan-ja/stan-ja#42]
Chapter02のプルリクをあげたのですが、以下のエラーが出ているようです。

https://github.com/stan-ja/stan-ja/pull/41 

`ci/circleci — No test commands were found`

@kos59125 さん、何か対応策はありますでしょうか？

**Comment by kos59125** [comment]
おそらく branch 作成元が古いので、最新の master を merge すると良いかと。

**Comment by soogie** [comment]
ありがとうございます。やってみます。

**Comment by soogie** [comment]
masterとマージしたら、大量の変更と、自分が翻訳したchap02でのコンフリクトが発生しました。

```
$ git branch
* create/part02/chap02
  create/part02/chap22
  create/part03/chap23
  fix/readme02
  master
$ git merge master
Auto-merging part02/chap02/chap02.md
CONFLICT (content): Merge conflict in part02/chap02/chap02.md
Automatic merge failed; fix conflicts and then commit the result.
```

次の手順としては以下を考えています。

まずchap02.mdの内容を精査して競合を解決してから

```
$ git push origin create/part02/chap02
```

@kos59125 さん、これで大丈夫でしょうか？

**Comment by kos59125** [comment]
良いと思います。

**Comment by soogie** [comment]
@kos59125 さん、ありがとうございました。無事create/part02/chap02にプッシュできました。
あげたばかりなのでCircleCIのチェックは未完了ですが、とりあえずチェック中にはなりました。

**Comment by soogie** [comment]
チェックもパスしたようなのでこのissueをクローズします。ご教示ありがとうございました。
