### ISSUE TITLE
取り込まれたが正常にpdfになっていない章がある

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-ja/stan-ja#43]
11章と12章で発生。原因究明中。
https://github.com/stan-ja/stan-ja/pull/38

**Comment by kos59125** [comment]
対応しました。やはり末尾の空行有無が問題だったようですね。
編集時に強制挿入するようにしたので、翻訳者での対応は不要です。

**Comment by kos59125** [comment]
PR を確認されたら、 PR のマージ・クローズとこの issue のクローズをお願いします。

**Comment by MatsuuraKentaro** [comment]
確認しました。ありがとうございます！
