### ISSUE TITLE
Stan 2.10対応

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-ja/stan-ja#46]
2.10がリリースされ、マニュアルも新しくなりました。以降の和訳については、2.9のマニュアルと章が1:1対応している場合は新しい2.10の方を訳したいと思います。いかがでしょうか。

過去に翻訳した部分の更新は、後回しにしてもよいかなと思っています。

**Comment by ito4303** [comment]
はい。でも、どの版を訳したか、 https://github.com/stan-ja/stan-ja/issues/31 にメモしておくとよいかもしれませんね。

**Comment by ito4303** [comment]
16章以降の章番号が変わったのですが、ディレクトリ構造はどうします?

**Comment by MatsuuraKentaro** [comment]
前者は了解です。章番号は困りましたね。時間があるときに、僕が一度に全部を修正するPull requestsを作成したいと思います。それまでは、2.9にあわせたディレクトリに作ってもらっていいでしょうか。中身だけ2.10から訳すということで…。

**Comment by MatsuuraKentaro** [comment]
いったんcloseします。
