### ISSUE TITLE
ロゴ

### ISSUE THREAD

**Issue by sinhrks** [stan-ja/stan-ja#54]
プロフィールのとこに貼りたかったので作りました。国旗イメージ。

![stanjp](https://cloud.githubusercontent.com/assets/1696302/17241665/fa831bb2-55ad-11e6-9545-c7cec75605d4.png)

**Comment by MatsuuraKentaro** [comment]
あざます！ロゴにします。一応ベタンコート氏には翻訳プロジェクトなど、Stanが広まる活動にはロゴを使ってよいと許諾をいただきましたので。

**Comment by MatsuuraKentaro** [comment]
反映しました。
